# Generated by Django 5.1.3 on 2024-12-10 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_proyectos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='año',
        ),
        migrations.RemoveField(
            model_name='categoriaproyecto',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='alumno',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_proyectos.proyectointegrador'),
        ),
        migrations.AlterField(
            model_name='categoriaproyecto',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
